/**
 * Trader creation and management tests
 * 
 * Tests the new flow where private keys are NOT required (agent wallet auto-generated).
 */

import { test, expect } from '@playwright/test';
import { setupApiMocks, setupApiErrors } from '../fixtures/api-handlers.js';
import { setupAuthenticatedState } from '../utils/auth-helpers.js';

test.describe('Trader Creation - Authenticated', () => {
  test.beforeEach(async ({ page }) => {
    await setupAuthenticatedState(page);
    await setupApiMocks(page);
  });

  test('trader creation page loads with form', async ({ page }) => {
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // Check page title
    await expect(page.getByRole('heading', { name: 'New trader' })).toBeVisible();

    // Form should be visible
    await expect(page.locator('form')).toBeVisible();
  });

  test('form displays trader name input', async ({ page }) => {
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // Check for name input - use label text since ID may be generated by form library
    const nameInput = page.getByLabel('Name (optional)');
    await expect(nameInput).toBeVisible();
  });

  test('form displays private key field', async ({ page }) => {
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // Private key field should exist
    const privateKeyInput = page.getByLabel('Private Key');
    await expect(privateKeyInput).toBeVisible();
  });

  test('displays account settings card', async ({ page }) => {
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // Check for account settings content
    await expect(page.getByText('Account Settings')).toBeVisible();
    await expect(page.getByText('Configure your wallet and copy target')).toBeVisible();
  });

  test('can create trader with valid data', async ({ page }) => {
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // Fill trader name
    const nameInput = page.getByLabel('Name (optional)');
    await nameInput.fill('My Test Trader');

    // Fill wallet address
    const walletInput = page.getByLabel('Wallet Address');
    await walletInput.fill('0x1234567890123456789012345678901234567890');

    // Fill private key
    const privateKeyInput = page.getByLabel('Private Key');
    await privateKeyInput.fill('0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd');

    // Fill copy address (address to copy trades from)
    const copyAddressInput = page.getByLabel('Copy Account Address');
    await copyAddressInput.fill('0xabcdefabcdefabcdefabcdefabcdefabcdefabcd');

    // Submit form
    const submitButton = page.getByRole('button', { name: 'Create Trader' });
    await submitButton.click();

    // Should redirect after successful creation
    await page.waitForURL(/\/traders/, { timeout: 5000 });
  });

  test('shows validation error when name is empty', async ({ page }) => {
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // Fill required fields but leave name empty
    const walletInput = page.getByLabel('Wallet Address');
    await walletInput.fill('0x1234567890123456789012345678901234567890');

    const privateKeyInput = page.getByLabel('Private Key');
    await privateKeyInput.fill('0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd');

    const copyAddressInput = page.getByLabel('Copy Account Address');
    await copyAddressInput.fill('0xabcdefabcdefabcdefabcdefabcdefabcdefabcd');

    // Try to submit
    const submitButton = page.getByRole('button', { name: 'Create Trader' });
    await submitButton.click();

    // Form should submit (name is optional) and redirect
    await page.waitForURL(/\/traders/, { timeout: 5000 });
  });

  test('exchange field defaults to Hyperliquid', async ({ page }) => {
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // The exchange is not a selectable field - Hyperliquid is the only supported exchange
    // Check that the form loads with Account Settings card
    await expect(page.getByText('Account Settings')).toBeVisible();
    await expect(page.getByText('Configure your wallet and copy target')).toBeVisible();
  });

  test('network field allows selection', async ({ page }) => {
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // Look for network selector
    const networkSelect = page.getByLabel('Network');
    await expect(networkSelect).toBeVisible();
    
    // Select mainnet
    await networkSelect.selectOption('mainnet');
    await expect(networkSelect).toHaveValue('mainnet');
    
    // Select testnet
    await networkSelect.selectOption('testnet');
    await expect(networkSelect).toHaveValue('testnet');
  });
});

test.describe('Trader Creation - Error Handling', () => {
  test.beforeEach(async ({ page }) => {
    await setupAuthenticatedState(page);
  });

  test('displays error message when API fails', async ({ page }) => {
    await setupApiErrors(page);
    await page.goto('/traders/new');
    await page.waitForLoadState('networkidle');

    // Fill form with valid data
    const nameInput = page.getByLabel('Name (optional)');
    await nameInput.fill('Test Trader');

    const walletInput = page.getByLabel('Wallet Address');
    await walletInput.fill('0x1234567890123456789012345678901234567890');

    const privateKeyInput = page.getByLabel('Private Key');
    await privateKeyInput.fill('0xabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd');
    
    const copyAddressInput = page.getByLabel('Copy Account Address');
    await copyAddressInput.fill('0xabcdefabcdefabcdefabcdefabcdefabcdefabcd');

    // Submit
    const submitButton = page.getByRole('button', { name: 'Create Trader' });
    await submitButton.click();

    // Should show error alert
    const errorAlert = page.locator('[role="alert"]');
    await expect(errorAlert).toBeVisible({ timeout: 5000 });
  });
});

test.describe('Trader List', () => {
  test.beforeEach(async ({ page }) => {
    await setupAuthenticatedState(page);
    await setupApiMocks(page);
  });

  test('can view traders list', async ({ page }) => {
    // Navigate to traders page
    await page.goto('/traders');
    await page.waitForLoadState('networkidle');

    // Wait for page heading to load (indicates auth completed)
    await expect(page.getByRole('heading', { name: 'Traders' })).toBeVisible();

    // Should show traders (mock API returns one trader)
    const traderItem = page.locator('text=Test Trader');
    await expect(traderItem).toBeVisible();
  });
});
