/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTradersIndexRouteImport } from './routes/_authenticated/traders/index'
import { Route as AuthenticatedTradersNewRouteImport } from './routes/_authenticated/traders/new'
import { Route as AuthenticatedTradersIdRouteImport } from './routes/_authenticated/traders/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradersIndexRoute =
  AuthenticatedTradersIndexRouteImport.update({
    id: '/traders/',
    path: '/traders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTradersNewRoute = AuthenticatedTradersNewRouteImport.update({
  id: '/traders/new',
  path: '/traders/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradersIdRoute = AuthenticatedTradersIdRouteImport.update({
  id: '/traders/$id',
  path: '/traders/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/traders/$id': typeof AuthenticatedTradersIdRoute
  '/traders/new': typeof AuthenticatedTradersNewRoute
  '/traders/': typeof AuthenticatedTradersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/traders/$id': typeof AuthenticatedTradersIdRoute
  '/traders/new': typeof AuthenticatedTradersNewRoute
  '/traders': typeof AuthenticatedTradersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/traders/$id': typeof AuthenticatedTradersIdRoute
  '/_authenticated/traders/new': typeof AuthenticatedTradersNewRoute
  '/_authenticated/traders/': typeof AuthenticatedTradersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/traders/$id'
    | '/traders/new'
    | '/traders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/traders/$id'
    | '/traders/new'
    | '/traders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/traders/$id'
    | '/_authenticated/traders/new'
    | '/_authenticated/traders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/traders/': {
      id: '/_authenticated/traders/'
      path: '/traders'
      fullPath: '/traders/'
      preLoaderRoute: typeof AuthenticatedTradersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/traders/new': {
      id: '/_authenticated/traders/new'
      path: '/traders/new'
      fullPath: '/traders/new'
      preLoaderRoute: typeof AuthenticatedTradersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/traders/$id': {
      id: '/_authenticated/traders/$id'
      path: '/traders/$id'
      fullPath: '/traders/$id'
      preLoaderRoute: typeof AuthenticatedTradersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTradersIdRoute: typeof AuthenticatedTradersIdRoute
  AuthenticatedTradersNewRoute: typeof AuthenticatedTradersNewRoute
  AuthenticatedTradersIndexRoute: typeof AuthenticatedTradersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTradersIdRoute: AuthenticatedTradersIdRoute,
  AuthenticatedTradersNewRoute: AuthenticatedTradersNewRoute,
  AuthenticatedTradersIndexRoute: AuthenticatedTradersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
